kind: VirtualClusterInstance
apiVersion: management.loft.sh/v1
metadata:
  name: vcluster3
  namespace: loft-p-default
spec:
  displayName: vcluster3
  owner:
    user: admin
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart: {}
      values: |-
        sync:
          ingresses:
            enabled: true

        coredns:
          integrated: true
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  clusterRef:
    cluster: loft-cluster
    namespace: loft-default-v-vcluster3
    virtualCluster: vcluster3
