kind: VirtualClusterInstance
apiVersion: management.loft.sh/v1
metadata:
  name: vcluster5
  namespace: loft-p-default
labels:
  pipekit/appset-vcluster: "true"
  vc-identifier: vc-timtest-1
spec:
  displayName: vcluster5
  owner:
    user: admin
  templateRef:
    name: my-template
  clusterRef:
    cluster: loft-cluster
    namespace: loft-default-v-vcluster5
    virtualCluster: vcluster5
